server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Next.js static export trailing slash
    location / {
        try_files $uri $uri.html $uri/ =404;
    }

    # 404 page
    error_page 404 /404.html;
}
